# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: base_model.h5
  UPDATED_BASE_MODEL_NAME: updated_base_model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks

data:
  source_url: https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip
  local_dir: data
  data_file: data.zip 
  #the url, local_dir and data_file are used to download the data from the url and save it in the local_dir with the name data_file{data.zip}
  unzip_data_dir: data #here we are extracting the data.zip file and saving it in the data folder. later we can change path if required.
  bad_data_dir: bad_data
  parent_data_dir: PetImages
  model_dir: model
  init_modal_file: init_model.h5

params:
  img_shape: [180, 180, 3] #if we use () it will treat as string. so use [] for list. later we can call in layer creation.
  lr : 0.001
  loss: sparse_categorical_crossentropy
  metrics: ["accuracy"]

  #we will save model in data folder only for now. 

